### ISSUE TITLE
Don't redirect to HTTP site on login

### ISSUE THREAD

**Issue by gsingh93** [vikramkhalsa/kirtan-programs-server#18]
The redirect [here](https://github.com/vikramkhalsa/kirtan-programs-server/blob/master/login.php#L26) forces HTTPS users back to an HTTP connection. The redirect can use a relative path to avoid this.

**Comment by vikramkhalsa** [comment]
https://github.com/vikramkhalsa/kirtan-programs-server/commit/409eebaeca5f149f2834a72a8af462c95f41d65d
