### ISSUE TITLE
Don't reveal whether user accounts exist on failed login

### ISSUE THREAD

**Issue by gsingh93** [vikramkhalsa/kirtan-programs-server#19]
When login fails, don't reveal to the user trying to login that the account exists: https://github.com/vikramkhalsa/kirtan-programs-server/blob/master/login.php#L36

An attacker can enumerate which accounts exist before attempting to guess their passwords.

**Comment by vikramkhalsa** [comment]
https://github.com/vikramkhalsa/kirtan-programs-server/commit/409eebaeca5f149f2834a72a8af462c95f41d65d
