### ISSUE TITLE
PHP Session ID cookie is not HTTPOnly

### ISSUE THREAD

**Issue by gsingh93** [vikramkhalsa/kirtan-programs-server#21]
The session ID cookie should be set to HTTPOnly to prevent it from being accessed from JS (XSS).

It should really have a secure flag as well, but that's only possible if you force everyone to use HTTPS (which you should).

**Comment by vikramkhalsa** [comment]
how can i force everyone to use https?

**Comment by gsingh93** [comment]
I think this will work for you: https://www.namecheap.com/support/knowledgebase/article.aspx/9770/38/how-to-force-https-using-htaccess-file-in-cpanel

**Comment by vikramkhalsa** [comment]
It worked! 

Awesome, thanks.
